//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarWPFProject.VehicleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/Common.Models")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CubicCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FuelConsuptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KilometersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CubicCapacity {
            get {
                return this.CubicCapacityField;
            }
            set {
                if ((this.CubicCapacityField.Equals(value) != true)) {
                    this.CubicCapacityField = value;
                    this.RaisePropertyChanged("CubicCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelField, value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FuelConsuption {
            get {
                return this.FuelConsuptionField;
            }
            set {
                if ((this.FuelConsuptionField.Equals(value) != true)) {
                    this.FuelConsuptionField = value;
                    this.RaisePropertyChanged("FuelConsuption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModel {
            get {
                return this.IdModelField;
            }
            set {
                if ((this.IdModelField.Equals(value) != true)) {
                    this.IdModelField = value;
                    this.RaisePropertyChanged("IdModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kilometers {
            get {
                return this.KilometersField;
            }
            set {
                if ((this.KilometersField.Equals(value) != true)) {
                    this.KilometersField = value;
                    this.RaisePropertyChanged("Kilometers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRentals {
            get {
                return this.TotalRentalsField;
            }
            set {
                if ((this.TotalRentalsField.Equals(value) != true)) {
                    this.TotalRentalsField = value;
                    this.RaisePropertyChanged("TotalRentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/Common.Models")]
    [System.SerializableAttribute()]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RentACarWPFProject.VehicleService.CarModel> ModelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RentACarWPFProject.VehicleService.CarModel> Models {
            get {
                return this.ModelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelsField, value) != true)) {
                    this.ModelsField = value;
                    this.RaisePropertyChanged("Models");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarModel", Namespace="http://schemas.datacontract.org/2004/07/Common.Models")]
    [System.SerializableAttribute()]
    public partial class CarModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleService.IVehicleService")]
    public interface IVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/AddNewCar", ReplyAction="http://tempuri.org/IVehicleService/AddNewCarResponse")]
        RentACarWPFProject.VehicleService.AddNewCarResponse AddNewCar(RentACarWPFProject.VehicleService.AddNewCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/AddNewCar", ReplyAction="http://tempuri.org/IVehicleService/AddNewCarResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.AddNewCarResponse> AddNewCarAsync(RentACarWPFProject.VehicleService.AddNewCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCars", ReplyAction="http://tempuri.org/IVehicleService/GetCarsResponse")]
        RentACarWPFProject.VehicleService.GetCarsResponse GetCars(RentACarWPFProject.VehicleService.GetCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCars", ReplyAction="http://tempuri.org/IVehicleService/GetCarsResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarsResponse> GetCarsAsync(RentACarWPFProject.VehicleService.GetCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCarByManufacturer", ReplyAction="http://tempuri.org/IVehicleService/GetCarByManufacturerResponse")]
        RentACarWPFProject.VehicleService.GetCarByManufacturerResponse GetCarByManufacturer(RentACarWPFProject.VehicleService.GetCarByManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCarByManufacturer", ReplyAction="http://tempuri.org/IVehicleService/GetCarByManufacturerResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarByManufacturerResponse> GetCarByManufacturerAsync(RentACarWPFProject.VehicleService.GetCarByManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCarByModel", ReplyAction="http://tempuri.org/IVehicleService/GetCarByModelResponse")]
        RentACarWPFProject.VehicleService.GetCarByModelResponse GetCarByModel(RentACarWPFProject.VehicleService.GetCarByModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetCarByModel", ReplyAction="http://tempuri.org/IVehicleService/GetCarByModelResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarByModelResponse> GetCarByModelAsync(RentACarWPFProject.VehicleService.GetCarByModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/DeleteCar", ReplyAction="http://tempuri.org/IVehicleService/DeleteCarResponse")]
        RentACarWPFProject.VehicleService.DeleteCarResponse DeleteCar(RentACarWPFProject.VehicleService.DeleteCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/DeleteCar", ReplyAction="http://tempuri.org/IVehicleService/DeleteCarResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.DeleteCarResponse> DeleteCarAsync(RentACarWPFProject.VehicleService.DeleteCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/UpdateCar", ReplyAction="http://tempuri.org/IVehicleService/UpdateCarResponse")]
        RentACarWPFProject.VehicleService.UpdateCarResponse UpdateCar(RentACarWPFProject.VehicleService.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/UpdateCar", ReplyAction="http://tempuri.org/IVehicleService/UpdateCarResponse")]
        System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.UpdateCarResponse> UpdateCarAsync(RentACarWPFProject.VehicleService.UpdateCarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddNewCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentACarWPFProject.VehicleService.Car car;
        
        public AddNewCarRequest() {
        }
        
        public AddNewCarRequest(RentACarWPFProject.VehicleService.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNewCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddNewCarResponse {
        
        public AddNewCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCars", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsRequest {
        
        public GetCarsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarsResult;
        
        public GetCarsResponse() {
        }
        
        public GetCarsResponse(System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarsResult) {
            this.GetCarsResult = GetCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByManufacturer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentACarWPFProject.VehicleService.Manufacturer manufacturer;
        
        public GetCarByManufacturerRequest() {
        }
        
        public GetCarByManufacturerRequest(RentACarWPFProject.VehicleService.Manufacturer manufacturer) {
            this.manufacturer = manufacturer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByManufacturerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarByManufacturerResult;
        
        public GetCarByManufacturerResponse() {
        }
        
        public GetCarByManufacturerResponse(System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarByManufacturerResult) {
            this.GetCarByManufacturerResult = GetCarByManufacturerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentACarWPFProject.VehicleService.CarModel model;
        
        public GetCarByModelRequest() {
        }
        
        public GetCarByModelRequest(RentACarWPFProject.VehicleService.CarModel model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarByModelResult;
        
        public GetCarByModelResponse() {
        }
        
        public GetCarByModelResponse(System.Collections.Generic.List<RentACarWPFProject.VehicleService.Car> GetCarByModelResult) {
            this.GetCarByModelResult = GetCarByModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentACarWPFProject.VehicleService.Car car;
        
        public DeleteCarRequest() {
        }
        
        public DeleteCarRequest(RentACarWPFProject.VehicleService.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int DeleteCarResult;
        
        public DeleteCarResponse() {
        }
        
        public DeleteCarResponse(int DeleteCarResult) {
            this.DeleteCarResult = DeleteCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentACarWPFProject.VehicleService.Car car;
        
        public UpdateCarRequest() {
        }
        
        public UpdateCarRequest(RentACarWPFProject.VehicleService.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdateCarResult;
        
        public UpdateCarResponse() {
        }
        
        public UpdateCarResponse(int UpdateCarResult) {
            this.UpdateCarResult = UpdateCarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleServiceChannel : RentACarWPFProject.VehicleService.IVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<RentACarWPFProject.VehicleService.IVehicleService>, RentACarWPFProject.VehicleService.IVehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentACarWPFProject.VehicleService.AddNewCarResponse AddNewCar(RentACarWPFProject.VehicleService.AddNewCarRequest request) {
            return base.Channel.AddNewCar(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.AddNewCarResponse> AddNewCarAsync(RentACarWPFProject.VehicleService.AddNewCarRequest request) {
            return base.Channel.AddNewCarAsync(request);
        }
        
        public RentACarWPFProject.VehicleService.GetCarsResponse GetCars(RentACarWPFProject.VehicleService.GetCarsRequest request) {
            return base.Channel.GetCars(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarsResponse> GetCarsAsync(RentACarWPFProject.VehicleService.GetCarsRequest request) {
            return base.Channel.GetCarsAsync(request);
        }
        
        public RentACarWPFProject.VehicleService.GetCarByManufacturerResponse GetCarByManufacturer(RentACarWPFProject.VehicleService.GetCarByManufacturerRequest request) {
            return base.Channel.GetCarByManufacturer(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarByManufacturerResponse> GetCarByManufacturerAsync(RentACarWPFProject.VehicleService.GetCarByManufacturerRequest request) {
            return base.Channel.GetCarByManufacturerAsync(request);
        }
        
        public RentACarWPFProject.VehicleService.GetCarByModelResponse GetCarByModel(RentACarWPFProject.VehicleService.GetCarByModelRequest request) {
            return base.Channel.GetCarByModel(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.GetCarByModelResponse> GetCarByModelAsync(RentACarWPFProject.VehicleService.GetCarByModelRequest request) {
            return base.Channel.GetCarByModelAsync(request);
        }
        
        public RentACarWPFProject.VehicleService.DeleteCarResponse DeleteCar(RentACarWPFProject.VehicleService.DeleteCarRequest request) {
            return base.Channel.DeleteCar(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.DeleteCarResponse> DeleteCarAsync(RentACarWPFProject.VehicleService.DeleteCarRequest request) {
            return base.Channel.DeleteCarAsync(request);
        }
        
        public RentACarWPFProject.VehicleService.UpdateCarResponse UpdateCar(RentACarWPFProject.VehicleService.UpdateCarRequest request) {
            return base.Channel.UpdateCar(request);
        }
        
        public System.Threading.Tasks.Task<RentACarWPFProject.VehicleService.UpdateCarResponse> UpdateCarAsync(RentACarWPFProject.VehicleService.UpdateCarRequest request) {
            return base.Channel.UpdateCarAsync(request);
        }
    }
}
